version: '1.0'
services:
  mongodb:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - dbdata:/data/db

  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - /redisdata

  zookeeper:
    container_name: ${ZOOKEPER_NAME}
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    container_name: ${KAFKA_NAME}
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "parse_streamers_topic:1:1, parse_streams_topic:1:1, parse_games_topic:1:1, parse_category_topic:1:1, parse_brand_topic:1:1, "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  dbdata:
